config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'       # /posts/2/vote
    end
  	resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
	include Sluggable
	has_many :post_categories
	has_many :posts, through: :post_categories

	validates :name, presence: true

	sluggable_column :name

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	include Voteable
	belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
	belongs_to :post
	has_many :votes, as: :voteable

	validates :body, presence: true
	
end

app/models/post.rb
class Post < ActiveRecord::Base
	include Voteable
	include Sluggable

	belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories


	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :url, presence: true, uniqueness: true

	sluggable_column :title

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	include Sluggable
	
	has_many :posts
	has_many :comments
	has_many :votes

	has_secure_password validations: false
	validates :username, presence: true, uniqueness: true
	validates :password, presence: true, on: :create, length: {minimum: 4} 
	# en update no se dispara esta validacion

	sluggable_column :username

	def admin?
		self.role == 'admin'
	end

		def moderator?
		self.role == 'moderator'
	end


end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
	belongs_to :voteable, polymorphic: true

	validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	# para que los metodos esten disponibles en los templates
	helper_method :current_user, :logged_in?

	def current_user
		# memoization: no corras el codigo si ya existe @current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:error] = "Must be logged in to do that"
			redirect_to root_path
		end
	end

	def require_admin
		access_denied unless logged_in? and current_user.admin?
	end

	def access_denied
		flash[:error] = "You can't do that"
		redirect_to root_path
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_user, only: [:new, :create]
	before_action :require_admin, only: [:new, :create]

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category has been created"
			redirect_to root_path
		else
			render :new
		end
	end

	def show
		@category = Category.find_by slug: params[:id]
	end

	def category_params
		params.require(:category).permit(:name)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :require_user

	def create
		@post = Post.find_by slug: params[:post_id]
		@comment = @post.comments.build(params.require(:comment).permit(:body))
		@comment.creator = current_user
		
		if @comment.save
			flash[:notice] = "your comment was added"
			redirect_to post_path(@post)
		else
			render 'posts/show'
		end
	end

	def vote
		comment = Comment.find(params[:id])
		vote = Vote.create(voteable: comment, creator: current_user, vote: params[:vote])
		if vote.valid?
			flash[:notice] = "Your vote was counted" 
		else
			flash[:error] = "You can only vote on a comment once"
		end
		redirect_back(fallback_location: root_path)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: [:show, :edit, :update, :vote]
	# require_user is in ApplicationController
	before_action :require_user, except: [:show, :index]
	before_action :require_creator, only: [:edit, :update]
	
	def index
		@posts = Post.all.sort_by{|x| x.total_votes}.reverse 
	end

	def show
		@comment = Comment.new
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.creator = current_user
		if @post.save
			flash[:notice] = 'Your post was created.'
			redirect_to posts_path
		else
			render :new
		end
	end

	def edit; end

	def update
		if @post.update(post_params)
			flash[:notice] = 'Your post was updated.'
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def vote
		@vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
		
		respond_to do |format|
			format.html do
				if @vote.valid?
					flash[:notice] = "Your vote was counted"
				else
					flash[:error] = "Youcan only vote on a post once"
				end
				redirect_back(fallback_location: root_path)
			end
			format.js # aqui ejecuta vote.js.erb
		end

	end
	
	def post_params
		params.require(:post).permit(:title, :url, :description, category_ids: [])
	end

	def set_post
		@post = Post.find_by(slug: params[:id])
	end

	def require_creator
		access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.where(username: params[:username]).first
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Welcome, You've logged in"
			redirect_to root_path
		else
			flash[:error] = "There is something wrong with your username or password"
			redirect_to login_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You've logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update]
	before_action :require_same_user, only: [:edit, :update]

	def new
		@user = User.new
	end

	def show
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "You are registered"
			redirect_to root_path
		else
			render :new
		end
	end

	def edit	
	end

	def update
		if @user.update(user_params)
			flash[:notice] = "Your profile was updated"
			redirect_to user_path(@user)
		else
			render :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :password, :time_zone)
	end

	def set_user
		@user = User.find_by slug: params[:id]
	end

	def require_same_user
		if current_user != @user
			flash[:error] = "You're not allowed to do that"
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def fix_url(str)
		str.starts_with?("http://") ? str : "http://#{str}"
	end

	def display_datetime(dt)
		if logged_in? && !current_user.time_zone.blank?
			dt = dt.in_time_zone(current_user.time_zone)
		end
		dt.strftime("%m/%d/%Y %l:%M%P %Z")
	end

end

app/views/categories/_category.html.erb
<span class="badge badge-pill badge-secondary badge-sm"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'New Category' %>
<%= render 'shared/errors', obj: @category %>

<div class="container">
	<%= form_for @category do |f| %>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<%= f.submit "Create category", class: 'btn btn-success' %>
	<% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
	<%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<div class="container">
		<div class="row mb-2 justify-content-center"> <!-- init row -->

					<div class="col"> <!-- init col -->

						<div class="card-body bg-light text-center">
							
							<%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post' do %>
								<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
								  <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z"/>
								</svg>
							<% end %>

							</br>
							<%= comment.total_votes %> votes
							</br>
							
							<%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post' do %>
								<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  							<path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  							<path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z"/>
								</svg>
							<% end %>

						</div> <!-- end card-body -->

					</div> 	 <!-- end col -->

					<div class="col-10"> <!-- init col -->


									<% show_post ||= false %>
									<div class="card-body bg-light">
										<em>"<%= comment.body %>"</em>
										<% if show_post %>
											on <%= link_to comment.post.title, post_path(comment.post) %>
										<% end %>
										<span class="quiet">posted by </span><%= link_to comment.creator.username, user_path(comment.creator) %>
												<small>
													<span>at <%= display_datetime(comment.created_at) %></span>
												</small>
										</span>
									</div> <!-- end card-body -->

					</div> <!-- end col-10 -->
	</div> <!-- end row -->
</div> <!-- end container -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == 'notice' ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
    <!-- Begin Bootstrap Navbar -->
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Postit!</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
 
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>


          <li class="nav-item dropdown">
            <%= link_to '#', class: 'nav-link dropdown-toggle', 'data-toggle' => 'dropdown' do %>
          Categories <span class='caret'></span>
            <% end %>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% Category.all.each do |category| %>
                <div>
                  <%= link_to category.name, category_path(category), class: 'dropdown-item' %>
                </div>
              <% end %>
              <% if logged_in? and current_user.admin? %>
                <div class="dropdown-divider"></div>
                  <%= link_to(new_category_path) do %>
                  <div class="dropdown-item">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                    </svg>
                    New category
                  </div>
                <% end %>
              <% end %>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>


          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>

          <% if logged_in? %>

            <li class="nav-item dropdown">
              <%= link_to('#', class: 'nav-link dropdown-toggle', 'data-toggle' => 'dropdown') do %>
                <%= current_user.username %> <span class='caret'></span>
              <% end %>

              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to edit_user_path(current_user) do %>
                        <div class="dropdown-item">

                         <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                          </svg>
                          Edit Profile
                        </div>

                    <% end %>


                <%= link_to user_path(current_user) do %>
                        <div class="dropdown-item">
                          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                          </svg>

                          Show Profile
                        </div>

                    <% end %>

                <%= link_to logout_path do %>
                        <div class="dropdown-item">
                          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-door-closed-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4 1a1 1 0 0 0-1 1v13H1.5a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2a1 1 0 0 0-1-1H4zm2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                          </svg>

                          Logout
                        </div>

                    <% end %>
              </div>
            </li>

            <li class='nav-item'>
              <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
            </li>

          <% else # logged out %>
            <li class='nav-item'>
              <%= link_to 'Register', register_path, class: 'btn btn-small' %>
            </li>
            <li class='nav-item'>
              <%= link_to 'Log in', login_path, class: 'btn btn-small' %>
            </li>
          <% end %>

        </ul>

      </div>
    </nav>
    
    <!-- End Bootstrap Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post%>

<div class='container'>
	<%= form_for @post do |f| %>
		<div class='form-group'>
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control'%>
		</div>
		<div class='form-group'>
			<%= f.label :url %>
			<%= f.text_field :url, class: 'form-control' %>
		</div>
		<div class='form-group'>
			<%= f.label :description %>
			<%= f.text_area :description, rows:5 , class: 'form-control'%>
		</div>
		<div class='form-group'>
			<%= f.label "Categories" %>
			<br>
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
			<% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
			<% end %>
		</div>
		<%= f.submit(@post.new_record? ? 'Create Post': 'Update Post', class: 'btn btn-primary') %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class="container">
		<div class="row mb-2 justify-content-center"> <!-- init row -->
					<div class="col"> <!-- init col -->

						<div class="card-body bg-light text-center">
							
							<%= link_to vote_post_path(post, vote: true), method: 'post' do %>
								<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								  <path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
								  <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z"/>
								</svg>
							<% end %>

							</br>
							<span id='post_<%=post.slug%>_votes>'	><%= post.total_votes %> votes</span>
							</br>
							
							<%= link_to vote_post_path(post, vote: false), method: 'post' do %>
								<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  							<path fill-rule="evenodd" d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  							<path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z"/>
								</svg>
							<% end %>

						</div> <!-- end card-body -->

					</div> 	 <!-- end col -->
				<div class="col-10">
					
					<div class="card-body bg-light">
						<%= render post.categories %>
						<h4><%= link_to post.title, fix_url(post.url) %></h4>
						<p><%= post.description %></p>
						<p>
							<span class="quiet">posted by </span><%= link_to post.creator.username, user_path(post.creator) %>
							<small>
								<span>at <%= display_datetime(post.created_at) %></span>
							</small>
							<span>
								<%= link_to("#{post.comments.size} comments", post_path(post)) %>
							</span>
						</p>
					</div> <!-- end card-body -->

			</div> <!-- end col-10 -->
		</div> <!-- end row -->
</div> <!-- end container -->

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>
<div class="container">

	<% @posts.each do |post| %>
		<%= render 'post', post: post %>
	<% end %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new Post' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
	<% if logged_in? %>
		<p class='pull-right'>
			[<%= link_to 'edit this post', edit_post_path(@post) %>]
		</p>
	<% end %>
	<p>
		<%= render @post.categories %>
	</p>
		<%= render 'shared/content_title', title: @post.title %>
	<p>
		<%= @post.description %>
	</p>
	<hr/>

		<% if logged_in? %>
			<%= form_for [@post, @comment] do |f| %>
				<%= render 'shared/errors', obj: @comment %>
				<div class="form-group">
					<%= f.label :body, 'Leave a comment'%>
					<%= f.text_area :body, rows: 3, class: 'span6' %>
				</div>
			<%= f.submit "Create Comment", class: 'btn btn-primary'%>
			<% end %>
		<% end %>

		<h5>Comments:</h5>
		<% @post.reload.comments.each do |comment| %>   <!-- para que los comments en memoria no validados no los contemple -->
			<%= render 'comments/comment', comment: comment %>
		<% end %>

	</div>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
    $("#post_<%=@post.slug%>_votes").html("<%= @post.total_votes %> votes")
<% else %>
    alert('Solo puedes votar una vez');
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
	<%= title %>
	<hr/>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class='container'>
		<div class='row'>
			<div class='alert alert-danger span12' >
				<h5>Please fix the following errors:</h5>
				<ul>
					<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<div class='container'>
		<%= form_for @user do |f| %>
			<%= render 'shared/errors', obj: @user %>
			<div class='form-group'>
				<%= f.label :username %>
				<%= f.text_field :username, class: 'form-control'%>
			</div>

			<div class='form-group'>
				<%= f.label :password %>
				<%= f.password_field :password, class: 'form-control'%>
			</div>

			<div class='form-group'>
				<%= f.label :time_zone %>
				<%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name , class: 'form-control'%>
			</div>

			<%= f.submit (@user.new_record? ? "Register": "Update profile"), class: 'btn btn-success' %>
		<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Edit profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class='container'>

	<dl class='dl-horizontal'>
		<dt>Username:</dt>
		<dd><%= @user.username %></dd>
				<dt>Time zone:</dt>
		<dd><%= @user.time_zone %></dd>
	</dl>

	<h5><%= @user.username %>'s Activity</h5>
	<ul class="nav nav-tabs">
		<li class="active nav-item">
			<% if params[:tab].nil? %>
				<%= link_to "Posts (#{@user.posts.size})", user_path(@user) ,class: 'nav-link active' %>
				<% else %>
				<%= link_to "Posts (#{@user.posts.size})", user_path(@user) ,class: 'nav-link' %>

			<% end %>
		</li>
		<li class='nav-item'>
			<% if params[:tab] == 'comments' %>
			<%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments'), class: 'nav-link active' %>
			<% else %>
						<%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments'), class: 'nav-link' %>
			<% end %>
		</li>
	</ul>

	<% if params[:tab].nil? %>
		<% @user.posts.each do |post| %>
			<%= render 'posts/post', post: post %>
		<% end %>
	<% elsif params[:tab] == 'comments' %>
		<% @user.comments.each do |comment| %>
			<%= render 'comments/comment', comment: comment, show_post: true %>
		<% end %>
	<% end %>

</div>